[package]
name = "rust-server"
version = "0.1.0"
authors = ["luke.simpson"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
# actix-files = "0.6.2"
reqwest = "0.11.14"